# Change these first
owner: meething # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Meething Site
    url: https://meething.space
  - name: US Meething
    url: https://us.meething.space
  - name: EU Meething
    url: https://eu.meething.space
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://user-images.githubusercontent.com/1423657/103484898-901a5000-4df2-11eb-9c19-fab32e5bd96c.png
  name: Meething
  introTitle: "**Meething Uptime**"
  introMessage: Status for Meething Services & Servers
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Meething
      href: https://meething.space

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
